<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\AggregatesTest\Interfaces\" />
    <Folder Include="Aggregates\AggregatesTest\Especifications\" />
    <Folder Include="Utils\" />
    <Folder Include="Shared\" />
  </ItemGroup>

</Project>
